[package]
name = "groth16-baseline"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.6.0"
ark-ff = "0.6.0"
ark-groth16 = { version = "0.6.0", features = ["print-trace"] }
ark-relations = "0.6.0"
ark-serialize = "0.6.0"
ark-std = "0.6.0"
ark-ec = "0.6.0"
ark-poly = "0.6.0"

[patch.crates-io]
ark-groth16 = { path = "vendor/ark-groth16" }

